directionsOfStudy:
- 09.04.03. Прикладная информатика
directionsOfStudyParagraph: 14
isCreateContractForOrganization: false
nameOfOrganization: (отсутствует)
periodOfPracticeParagraph: 17
typesOfPractice:
- duration: '207'
  type: Учебная практика
- duration: '207'
  type: Производственная практика
- duration: '315'
  type: Дипломная практика
typesOfPracticeParagraph: 17
